### ISSUE TITLE
Sun tracking Process Need to Reduce to 10 seconds

### ISSUE THREAD

**Issue by Bosebcc** [Bosebcc/Realsat#38]
#37

**Comment by Bosebcc** [comment]
**Easy Solution**
- [ ]  Increase the amount of angle per step(greater chance to miss the sun)

**Complicated Solution**
- [ ] As the UV increase, decrease the angle per step
- [ ] Record the servo position when UV is the highest(while doing non-detail scan) then come back and scan at the point again (now: instead of moving both the servo and stepper, move only the stepper to adjust the angle)

**Comment by Bosebcc** [comment]
Allow servo to measure UV both clockwise and counterclockwise
Test Code(Awaiting Testing) : 👍 https://github.com/Bosebcc/Realsat/commit/7c1600117633e52bdd8e4c8fb47082151b50dfce

**Comment by Bosebcc** [comment]
👎 
https://github.com/Bosebcc/Realsat/commit/7c1600117633e52bdd8e4c8fb47082151b50dfce
Not working : The servo is not turning properly (Suspicion: The pulse width is conflicting

**Comment by Bosebcc** [comment]
👍 https://github.com/Bosebcc/Realsat/commit/ad2c9b2554dbc108e5776e9f6b04682acb3366a5
Reduce to 15 seconds: Reduce Accuracy (20 --> 24 degrees per turn)

<img width="334" alt="screen shot 2018-07-31 at 13 37 35" src="https://user-images.githubusercontent.com/32533504/43442028-f18d58ba-94c6-11e8-8c36-cbff03e8933d.png">

<img width="352" alt="screen shot 2018-07-31 at 13 37 44" src="https://user-images.githubusercontent.com/32533504/43442039-f709d4c6-94c6-11e8-8b84-46423396df5d.png">
